### ISSUE TITLE
Using a polyfill library to support Promises

### ISSUE THREAD

**Issue by adapap** [StevensSEC/stevens-web-extension#20]
Promises are a way to reduce [callback hell](http://callbackhell.com/) in JavaScript. Asynchronous programming has become easier to write in modern day JS, using Promises and the async/await syntax.
[This polyfill](https://github.com/mozilla/webextension-polyfill) provides support for Promises in the chrome (as well as other browsers') API. This means that rather than nesting callback functions of hoisting them and polluting the namespace, we can just chain promises using `async`, `await`, and `.then`.

Since the project is relatively fresh, I think it would be worth considering this implementation for the following reasons:
- Makes code more readable by reducing nesting
- Simplifies handing errors using the `rejected` component of a Promise
- Easier to learn asynchronous programming for beginners using async/await

Should we consider implementing this library?

**Comment by adapap** [comment]
Additional benefit to using promises:
- Easier to write shared code to access common extension functionality such as retrieving items from storage or adding a listener for an alarm

**Comment by dyc3** [comment]
Why can't we just use promises? Why do we need a polyfill for it?

**Comment by adapap** [comment]
Promises are [not supported](https://stackoverflow.com/questions/42191030/promise-support-for-chrome-extensions-api) by Chrome extension API.
